### ISSUE TITLE
Help for JsonIdentityInfo

### ISSUE THREAD

**Issue by badetitou** [outfoxx/jackson-js#2]
Hi, I see that you are active on this project @kdubb.
I have a bug with JsonIdentifyInfo. It would be super nice if you can help me with it: https://github.com/pichillilorenzo/jackson-js/issues/22
I have no clue how to solve it

**Comment by kdubb** [comment]
First I would suggest trying the NPM package `@outfoxx/jackson-js`. That is our package that has all of our fixes applied cumulatively. If that doesn't work, a minimal project that reproduces the issue would be my next request.

**Comment by badetitou** [comment]
Thanks for your help!

I have tested your package without success (does not solve the problem)

I have created a minimal project with the issue: https://github.com/badetitou/example-angular-JsonIdentifyInfo.

After installing the project, running `npm run build` does work because it does not use _aot_.
running `npm run build:prod` does **not** work because it uses _aot_.

The angular reported issue is: 
```
ERROR in @outfoxx/jackson-js/dist/decorators/JsonIdentityInfo.ts(83,22): Error during template compile of 'JsonIdentityInfo'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
```

The corresponding Angular documentation page is: https://angular.io/guide/aot-metadata-errors#only-initialized-variables-and-constants

Whereas I understand the error, I have no clue how to fix it

**Comment by badetitou** [comment]
It looks like moving to Angular 9 fixes the bug
https://github.com/angular/angular/issues/14323#issuecomment-569060561
I tried it and it works in my simple example.

Sorry for the issue
